---
# file: roles/docker/tasks/main.yml
- name: disable selinux
  selinux: state=disabled
  when: ansible_os_family == "RedHat" and disable_selinux == true
  sudo: yes
  tags:
      - docker

- include: epl.yml
  when: binary != true

- include: binary.yml
  when: binary == true

- include: certs.yml

- name: Install BTRFS Support
  yum: name={{ item }} state=latest
  when: enable_btrfs == true
  with_items:
    - btrfs-progs
    - bridge-utils
  tags:
    - packages

- name: Create docker.socket directory path
  command: mkdir -p "{{ docker_socket_directory }}"
  sudo: yes
  tags:
      - docker

- name: Create docker.socket unit
  template: src=docker.socket dest=/etc/systemd/system/docker.socket owner=root group=root mode=0644
  sudo: yes
  notify: 
      - reload systemctl
      - restart docker socket
  tags:
    - docker

- name: Link docker.socket to standard location
  file: src={{ docker_socket_directory }}/docker.sock
        dest=/var/run/docker.sock
        state=link
        force=yes
  sudo: yes
  tags: 
    - docker
  when: docker_socket_directory != "/var/run"

- name: docker.service
  template: src=docker.service dest=/etc/systemd/system/docker.service owner=root group=root mode=0644
  sudo: yes
  notify: 
      - reload systemctl
      - restart docker
  tags:
      - docker

- name: Add Docker Users to Docker Group
  user: name={{ item }} groups=docker append=yes
  with_items: docker_users
  sudo: yes
  tags:
      - docker

- meta: flush_handlers

- name: Enable & Start Services
  service:  name={{ item }} state=started enabled=yes
  with_items:
      - docker.socket
      - docker.service
  sudo: yes
  tags:
    - docker
